//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventsID { get; set; }
        public string EventName { get; set; }
        public int RsvpID { get; set; }
    
        public virtual RSVP RSVP { get; set; }
    }
}
